<?php

namespace ProjetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AutocompRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutocompRepository extends EntityRepository
{
	public function recherche($autocomp)
	{
    	$qb = $this->createQueryBuilder('u');
    	$qb->select('u')
			->where('u.name LIKE :autocomp')
			->setParameter('autocomp', '%'.$autocomp.'%');

    return $qb->getQuery()->getResult();
	}
}
