<?php

namespace ProjetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteurRepository extends EntityRepository
{
}
